### ISSUE TITLE
Default OBody_presetDistributionConfig being ignored

### ISSUE THREAD

**Issue by vicscera** [audriuska12/OBodyMerger#1]
Not sure if this is intended or not, but it kind of defeats the purpose if the original config file gets overwritten, it's possible to preserve it by copying it into the `SKSE\Plugins\OBodyTemplate` folder before running the patcher although that's a preemptive step the end user would have to take, could reading that original file's contents be made into an option or even the default behavior? Thank you so much for making this patcher, by the way!

**Comment by audriuska12** [comment]
Hm. Good point. I was thinking of having the final one being assembled from the templates, and anyone using this would have their custom setup right in there (my hope is that eventually authors of mods like ORefit will just make two copies of their .json for this). Preserving the old values would have some presets stay in your config even if the source template was deleted, which is not a behaviour _I_ want, but I guess I can see why someone would want that.

Think I'll just add a config option to make a copy of the current file, if it exists, and use it as the basis for the new setup. Shouldn't be difficult.

**Comment by audriuska12** [comment]
Right, believe that's done.
